# Setup
title:        Quick Translator Replay
tagline:      An open source project for converting Chinese to Vietnamese
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       p-le
  url:        https://github.com/p-le/quick-translator-replay

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-cayman